-- Purpose: Remove the CORTEX_USAGE schema and all monitoring objects
-- WARNING: This will permanently remove all monitoring views, tables, and tasks
-- Safe to run: Multiple times (uses IF EXISTS), no impact on source data
-- Follows: Cleanup Rule - Must drop ONLY project-created objects, preserve database
-- Step 1: Verify current objects before cleanup
-- Step 2: Suspend all tasks before dropping (required)
-- Step 3: Drop the CORTEX_USAGE schema (includes all views, tables, tasks)
-- Step 4: Post-Cleanup Verification
-- Re-deployment

--   ✅ SNOWFLAKE_EXAMPLE.CORTEX_USAGE schema
--   ✅ 16 monitoring views (V_CORTEX_ANALYST_DETAIL, V_CORTEX_SEARCH_DETAIL, etc.)
--   ✅ 1 snapshot table (CORTEX_USAGE_SNAPSHOTS)
--   ✅ 1 serverless task (TASK_DAILY_CORTEX_SNAPSHOT)
--
-- What Was PRESERVED (Cleanup Rule):
--   ✅ SNOWFLAKE_EXAMPLE database (preserved per cleanup rule)
--   ✅ Source data in SNOWFLAKE.ACCOUNT_USAGE (read-only, untouched)
--   ✅ Customer data and applications (not affected)
--   ✅ Warehouses, users, roles (not affected)
--   ✅ All other schemas in SNOWFLAKE_EXAMPLE (not affected)
